title: ĤøŅĐΔj̆₀
author: Arĥimedeς ℳontegasppα
email: batalema@cacilhas.info
description: >
  Projeto de um sistema para jogos de RPG
baseurl: ""
url: https://hondaj.cacilhas.info/
twitter_username: Montegasppa
github_username: cacilhas
facebook_username: rodrigo.cacilhas
youtube_username: rodrigocacilhas

# Build settings
timezone: America/Sao_Paulo
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  style: compressed

paginate: 5
paginate_path: /page:num

disqus:
  shortname: hondaj

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
