title: ĤøŅĐΔj̆₀
author: Arĥimedeς ℳontegasppα
email: montegasppa@cacilhas.cc
description: >
  Projeto de um sistema para jogos de RPG
baseurl: ""
url: https://hondaj.cacilhas.cc/
twitter_username: Montegasppa
github_username: cacilhas
facebook_username: rodrigo.cacilhas
youtube_username: rodrigocacilhas

# Build settings
timezone: America/Sao_Paulo
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  style: compressed
  sass_dir: ./assets

paginate: 5
paginate_path: /page/:num

disqus:
  shortname: hondaj

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
