title: Ĥondaj’
email: batalema@cacilhas.info
description: >
  Projeto de um sistema para jogos de RPG
baseurl: ""
url: "//hondaj.cacilhas.info/"
twitter_username: Montegasppa
github_username: cacilhas
facebook_username: rodrigo.cacilhas
youtube_username: rodrigocacilhas

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: hondaj

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
